name: PHP Composer

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: darmats/php:7.3-apache-dev

    steps:
    - name: PHP Version
      run: php -v

    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/phpunit
